service: b4b-test
provider:
  name: aws
  region: 'eu-west-3'
  runtime: nodejs20.x
  stage: ${opt:stage,'dev'}
  timeout: 60
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_ENV: 'production'
  httpApi:
    cors: true

functions:
  api:
    handler: src/app/server.handler
    events:
      - httpApi: '*'
    environment:
      APP_KEY: ${env:APP_KEY}

custom:
  serverless-offline:
    allowCache: true
    httpPort: 4000
  serverlessSsmFetch:
    APP_KEY: /b4b-api/dev/APP_KEY

useDotenv: true

build:
  esbuild: false

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  # - serverless-dotenv-plugin
  # - serverless-ssm-fetch
  # - serverless-layers # Helps reduce deployment time study later
